language: node_js
node_js:
  - "0.12"
services:
  - mongodb
notifications:
  email: false
script:
  - npm test
after_script:
  - npm run cov
env:
  global:
    # FIREBASE_TOKEN
    - secure: LAbG4l7HAlx8qCzyJB8pYdq63NTSyIwGNf7NXtItHteuGON8DMd/Imb8x9wj5zSkur51ovDtg2SP4JWPeeJJkS45M3QI6jyChj4f/YF2KQI5I1UoMlYrqocTW1bOkCCvePD1HxtWpyNHD5XziUREhb9zx3wkxGh+eQP+pLEhi5WnpDe7/lawIoGUp8gGqXVNgNAzvVv4HNS/q3UBhB8YpxixpZJ1PuL47HeBXkgqCdhCFNeZWOUtM3XYWoQqepEkxnM+dnh0OHLA/2imWuQG0IDpm1PfUU4/Jgh1OL9gqcDWLDEfDD6paJTG20zwX4mk+4avU8dao5JANOfzoAEvExAyufscMUjBzl+IZRWdBQ/cbfUorNwUSi3DYxNG/1p1AlRxdFNuFeoH97kw07zvdjT5cuE0U1uv8LsH69oVwglgVkDPtViKkw5fy3Xuzsvzs9n28+xLqFvpmePlGRpRzx9zJu6D/hWw+E/ID8VKmHzBPBqQcxDmebsxG1Z26ox2iUHmU58h7UAvCF+APRSqsAxl3gyOMMc2tT1K/LmW3IAB1HhDdUWaocJbOT5ET/wjJBu3leQk0N9GQP2YFLeGbkr2BbUfU/+hGs3Wuq0XgQHGIhL5JRtSzBA8uppEnx5odHS36pzyB/zRdmz2e+uAVtbvg1KFZ7eZFQ3RUgMER6E=
    # FIREBASE_SECRET
    - secure: I9eIImQoMsDi54kU7Ty8xEKgt82Te0WSWcEPWgeMMYVNQb15I9yj1mcDp7CUlF/GvxL9cM4Q9f6oDoSxY4vFXDomCXs1h2NWOcWo9q8F/Kx86CUgx8ScD7u2Py+2VaJdvYCE2/Q0jIszlXtHAsZyXg8b6myZmSyhJyAstWr9mvEXt9w9oEDlB+McFUILUil5vMQqyTsGnxqBSeEaSnW/tJfxn/MVES/TD7sHo8lmywD4/IifCAICSOLw5H76UjhLmzZc3i/v+HyXakKJfZn895/XvuGqKYjgLOcoWmRpFfLQzQmQwbIQAhuR7IrTEYr64KKZd2L9vTkgslLyMiTpnQLKWoWjkLWNgrZ+J1DDQ9faBWpBycNyCcrQIZGFOAlaYCM1jJ5kralRjqwWxDGEqL52NNs5b9Nr0pu8xZZ5Yj9FKN5nbz1pEFQ0EGNLKjxFd/+5Qo972ZSlzeq9K97b84ZMsW/I78sHH8NOHFdHlcqEemqZqaJ7eH+mTO7fsvSsQoYmiL6LTQl9NHMOCPbSfMUd4Nhs2Aeg6T0cK81290jnuSHSfFfWrdUpk9nPstPvgqnlHvIAu1rOYyIqI0tFPV1Ag44abXlev21qlYVP+LoJb3n6sFK/usMENirpy3y/JUtdIY5kqODCuiDR+0iSPJFwOo4nA5cOVa0TOrvWmjE=
